<div id="content">
	<p>There are multiple versions of SnipSniper currently available (Click on one to direct-download the latest stable release):</p>
	<p>- <a href="https://github.com/CaptureCoop/SnipSniper/releases/latest/download/SnipSniper.jar">Java Standalone</a> (The classic Version of SnipSniper, all you generally need)</p>
	<p>- <a href="https://github.com/CaptureCoop/SnipSniper/releases/latest/download/SnipSniper_Installer_Win.exe">Windows Installer</a> (SnipSniper + Java in one package)</p>
	<p>- <a href="https://github.com/CaptureCoop/SnipSniper/releases/latest/download/SnipSniper_Portable_Win.zip">Windows Portable</a> (The same as above, but portable)</p>
	</br>
	<p>We also offer this link for a direct jar download of the latest Java Standalone release: <a href="/l/dl">https://SnipSniper.net/l/dl</a></p>
	</br>
	<p>Additionally we also have automated builds which mirror the latest dev builds generated by GitHub</p>
	<p>You can find the folder under <a href="/jars">SnipSniper.org/jars/</a> and the latest Download <a href="/jars/SnipSniper.jar">here</a></p>
	</br>
	<p>You can get manual downloads from multiple sources:</p>
	<p>- <a href="https://github.com/CaptureCoop/SnipSniper/releases" target="_blank">GitHub releases</a></p>
	<p>- <a href="https://github.com/CaptureCoop/SnipSniper/actions/workflows/dev.yml" target="_blank">Latest GitHub Actions dev build</a></p>
</div>
